### ISSUE TITLE
Cannot download puppet catalog

### ISSUE THREAD

**Issue by qdii** [voxpupuli/container-puppetserver#99]
Version: ghcr.io/voxpupuli/container-puppetserver:7.17.0-v1.5.0

On client nodes:

```
❯ puppet catalog download --debug
Debug: Runtime environment: puppet_version=7.31.0, ruby_version=3.0.6, run_mode=user, openssl_version='OpenSSL 3.1.1 30 May 2023', openssl_fips=false, default_encoding=UTF-8
Debug: Resolving service 'puppet' using Puppet::HTTP::Resolver::Settings
Debug: Verified CA certificate 'CN=Puppet Root CA: 6a3f66024e7244' fingerprint (SHA256) 2A:D8:E4:76:24:EF:28:72:55:CF:B0:B0:AE:04:8D:74:24:CC:21:37:23:31:C4:A4:E4:9B:0E:55:7D:6F:EF:5A
Debug: Verified CA certificate 'CN=Puppet CA generated on puppet at 2024-07-13 14:29:33 \+0000' fingerprint (SHA256) A1:CE:9C:A7:96:E1:6A:B7:BE:5F:D8:F1:48:34:0B:05:A0:AB:3B:53:F6:DF:C8:4B:B6:24:78:16:2D:59:F1:C3
Debug: Verified client certificate 'CN=del.dodges.it' fingerprint (SHA256) 25:DF:0E:C3:EF:20:65:78:25:9D:16:F9:07:2F:B6:48:07:BE:80:66:AF:04:82:38:8A:52:CC:10:9D:9A:D9:73
Debug: Using CRL 'CN=Puppet CA generated on puppet at 2024-07-13 14:29:33 \+0000' authorityKeyIdentifier '' crlNumber '0'
Debug: Using CRL 'CN=Puppet Root CA: 6a3f66024e7244' authorityKeyIdentifier '' crlNumber '0'
Debug: Creating new connection for https://puppet.dodges.it:8140
Debug: Starting connection for https://puppet.dodges.it:8140
Debug: Using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256
Debug: Caching connection for https://puppet.dodges.it:8140
Debug: Resolved service 'puppet' to https://puppet.dodges.it:8140/puppet/v3
Notice: Requesting catalog from puppet.dodges.it:8140 (5.196.26.88)
Debug: Evicting cache entry for environment :production
Debug: Deleted text domain :production: false
Debug: catalog supports formats: rich_data_json json rich_data_msgpack msgpack pson yaml dot
Debug: Using cached connection for https://puppet.dodges.it:8140
Debug: HTTP POST https://puppet.dodges.it:8140/puppet/v3/catalog/del.dodges.it?environment=production returned 500 Server Error
Debug: Caching connection for https://puppet.dodges.it:8140
Notice: Catalog compiled by puppet.ppt.svc.cluster.local
Error: Could not call 'find' on 'catalog': Error 500 on SERVER: Server Error: Could not intern from json: undefined method `[]' for nil:NilClass
Error: Could not call 'find' on 'catalog': Error 500 on SERVER: Server Error: Could not intern from json: undefined method `[]' for nil:NilClass
Error: Try 'puppet help catalog download' for usage
```

On puppetserver:

```
│ puppet-puppetserver 2024-07-22 19:44:01,491 ERROR [puppetserver] Puppet Server Error: Could not intern from json: undefined method `[]' for nil:NilClass                                                 │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node/facts.rb:43:in `initialize_from_hash'                                                                                        │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node/facts.rb:86:in `from_data_hash'                                                                                              │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/formats.rb:136:in `data_to_instance'                                                                                      │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/formats.rb:119:in `intern'                                                                                                │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/format_support.rb:12:in `convert_from'                                                                                    │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:119:in `convert_wire_facts'                                                                        │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:31:in `block in extract_facts_from_request'                                                        │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'                                                                                  │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'                                                                                                  │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:29:in `extract_facts_from_request'                                                                 │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:48:in `find'                                                                                       │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:223:in `find'                                                                                           │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:120:in `do_find'                                                                            │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:53:in `block in call'                                                                       │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'                                                                                                       │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'                                                                                                              │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:52:in `call'                                                                                │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/server/v3.rb:17:in `block in wrap'                                                                               │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `block in process'                                                                                    │
│ puppet-puppetserver org/jruby/RubyArray.java:1865:in `each'                                                                                                                                              │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'                                                                                             │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:88:in `process'                                                                                             │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:88:in `process'                                                                                             │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:86:in `block in process'                                                                                  │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:69:in `block in with_request_profiling'                                                                   │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'                                                                                  │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'                                                                                                  │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:65:in `with_request_profiling'                                                                            │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:85:in `block in process'                                                                                  │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:92:in `respond_to_errors'                                                                                 │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:84:in `process'                                                                                           │
│ puppet-puppetserver uri:classloader:/puppetserver-lib/puppet/server/master.rb:69:in `block in handleRequest'                                                                                             │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'                                                                                                       │
│ puppet-puppetserver /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'                                                                                                              │
│ puppet-puppetserver uri:classloader:/puppetserver-lib/puppet/server/master.rb:68:in `handleRequest'                                                                                                      │
│ puppet-puppetserver 10.244.226.142 - - - 22/Jul/2024:19:44:01 +0000 "POST /puppet/v3/catalog/del.dodges.it?environment=production HTTP/1.1" 500 123 10.244.226.142 10.244.226.142 8140 7   
```

**Comment by rwaffen** [comment]
I will wait for https://github.com/puppetlabs/puppet/pull/9424 being released and then will test again

**Comment by rwaffen** [comment]
does work now with puppet agent 8.9.0 and 7.33.0

```
root@crafty-testing:/# puppet --version
7.33.0

root@crafty-testing:/# puppet catalog download
Notice: Requesting catalog from puppet:8140 (172.18.0.3)
Notice: Catalog compiled by puppet
Notice: Saved catalog for crafty-testing to /opt/puppetlabs/puppet/cache/client_yaml/catalog/crafty-testing.yaml
```
